name: Build project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Jinja2
        run: pip install jinja2

      - name: Configure CMake
        run: cmake -B build -A x64

      - name: Build
        run: cmake --build build --config Release
