name: Build project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Jinja2
        run: pip install jinja2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: build
          options: |
            CMAKE_BUILD_TYPE=Release
            -G "Visual Studio 17 2022"
            -A x64

      - name: Build Solution with MSBuild
        run: |
          msbuild build/OreRenderer.sln /p:Configuration=Release /p:Platform=x64
        shell: cmd
